### ISSUE TITLE
Support for large buffers (>2G/4G)

### ISSUE THREAD

**Issue by bsergean** [4kills/go-libdeflate#11]
Hi there,

Thank you for making this package, libdeflate is very fast. Have you tried to decompress buffers that are larger than 4G ?

Some functions work with ints, so I wonder how things will work if the decompressed buffer is larger than what an int can hold.

```
// DecompressGzip interfaces with c libdeflate for gzip decompression
func DecompressGzip(dc *C.decomp, inAddr, outAddr *byte, inSize, outSize int, sPtr uintptr) error {
    return parseResult(C.res(C.libdeflate_gzip_decompress(dc,
        unsafe.Pointer(inAddr), intToInt64(inSize),
        unsafe.Pointer(outAddr), intToInt64(outSize),
        C.mkPtr(C.size_t(sPtr)),
    )))
}
```

**Comment by 4kills** [comment]
Hi there,

sorry for the super super late reply. Somehow, I haven't received notifications of your issues and have, therefore, overlooked it. 

I hope this is still relevant. Have you tested if it works as intended with >4GiB buffers? I believe it should. 

This is because, in Go, an `int` is platform-**dependant**, meaning it will be either 32 or 64 bit in length depending on whether you use a 32 or 64 bit architecture. I thought there was no point in giving 32-bit architectures the ability to use 64 bit buffers, since their memory can only hold 4 GiB anyways, and this library only works with in-memory buffers. 

If you have any concerns why this should create an issue, let me know.

**Comment by bsergean** [comment]
You were right, I think the problem was on my side. Thanks for checking.
